### ISSUE TITLE
JavaScript heap out of memory

### ISSUE THREAD

**Issue by xodus0721** [lemonlabdev/tumblbug_clone#5]
<--- Last few GCs --->

[12840:0000021E4DCBF520]    21452 ms: Mark-sweep 2044.2 (2051.4) -> 2044.2 (2051.4) MB, 611.4 / 0.0 ms  (average mu = 0.276, current mu = 0.227) allocation failure GC in old space requested
[12840:0000021E4DCBF520]    22257 ms: Mark-sweep 2044.2 (2051.4) -> 2044.2 (2051.4) MB, 594.2 / 0.0 ms  (average mu = 0.269, current mu = 0.262) last resort GC in old space requested

<--- JS stacktrace --->

==== JS stack trace =========================================

    0: ExitFrame [pc: 00007FF76C454DDD]
Security context: 0x017d182008d1 <JSObject>
    1: createElement(aka createElement) [0000005ED341CFC1] [D:\clone\tumblbug_clone\node_modules\react\cjs\react.development.js:~727] [pc=0000015EE721F989](this=0x018c36ac04b1 <undefined>,0x018be6e41841 <JSFunction HeaderTextButton (sfi = 0000001EBC87A149)>,0x003e534ffc91 <Object map = 0000000A0CC3F279>,0x03f5a2f3ff39 <Object map = 0000000A0CC3E199>)
    2...

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory

Writing Node.js report to file: report.20200730.162024.12840.0.001.json
Node.js report completed
 1: 00007FF76B85363F napi_wrap+128063
 2: 00007FF76B7F2836 public: bool __cdecl v8::base::CPU::has_sse(void)const __ptr64+35142
 3: 00007FF76B7F34F6 public: bool __cdecl v8::base::CPU::has_sse(void)const __ptr64+38406
 4: 00007FF76C009F4E private: void __cdecl v8::Isolate::ReportExternalAllocationLimitReached(void) __ptr64+94
 5: 00007FF76BFF2021 public: class v8::SharedArrayBuffer::Contents __cdecl v8::SharedArrayBuffer::Externalize(void) __ptr64+833
 6: 00007FF76BEBE57C public: static void __cdecl v8::internal::Heap::EphemeronKeyWriteBarrierFromCode(unsigned __int64,unsigned __int64,class v8::internal::Isolate * __ptr64)+1436
 7: 00007FF76BEC97D0 public: void __cdecl v8::internal::Heap::ProtectUnprotectedMemoryChunks(void) __ptr64+1312
 8: 00007FF76BEC62F4 public: static bool __cdecl v8::internal::Heap::PageFlagsAreConsistent(class v8::internal::HeapObject)+3204
 9: 00007FF76BEBBB13 public: bool __cdecl v8::internal::Heap::CollectGarbage(enum v8::internal::AllocationSpace,enum v8::internal::GarbageCollectionReason,enum v8::GCCallbackFlags) __ptr64+1283
10: 00007FF76BEBAF04 public: void __cdecl v8::internal::Heap::CollectAllAvailableGarbage(enum v8::internal::GarbageCollectionReason) __ptr64+196
11: 00007FF76BEBA204 public: void __cdecl v8::internal::Heap::AddRetainedMap(class v8::internal::Handle<class v8::internal::Map>) __ptr64+2580
12: 00007FF76BEDB36D public: class v8::internal::Handle<class v8::internal::HeapObject> __cdecl v8::internal::Factory::NewFillerObject(int,bool,enum v8::internal::AllocationType,enum v8::internal::AllocationOrigin) __ptr64+61
13: 00007FF76BC40ADF public: class v8::internal::interpreter::JumpTableTargetOffsets::iterator & __ptr64 __cdecl v8::internal::interpreter::JumpTableTargetOffsets::iterator::operator=(class v8::internal::interpreter::JumpTableTargetOffsets::iterator && __ptr64) __ptr64+1295
14: 00007FF76C454DDD public: virtual bool __cdecl v8::internal::SetupIsolateDelegate::SetupHeap(class v8::internal::Heap * __ptr64) __ptr64+546637
15: 0000015EE721F989
error Command failed with exit code 134.

**Comment by xodus0721** [comment]
Making HeaderTextButton, I used HeaderTextButton tag Instead of TextButton.

**Comment by plantstoen** [comment]
오늘의 교훈 : 컴포넌트 안에 컴포넌트명과  똑같은 이름을 가진 스타일드 컴포넌트를 만들지 맙시다..

**Comment by xodus0721** [comment]
컴포넌트 안에 컴포넌트명과 똑같은 이름을 가진 스타일드 컴포넌트를 만든게 아니라 그냥 잘못 쓴거 ㅋㅋㅋ....
